Participant tracker performance
sparc-request/sparc-fulfillment pull request #1032
Opened 2022-08-21 14:33 UTC by 6reg

https://www.pivotaltracker.com/story/show/180541541

2023-02-27 15:42 UTC, amcates commented on app/models/protocols_participant.rb
> +    self.can_be_destroyed
Pretty sure you can just remove this method.  Rails automatically creates ? methods for boolean attributes.  Please test this and remove the method if possible.

2023-02-27 19:50 UTC, 6reg commented on app/models/protocols_participant.rb
> +    self.can_be_destroyed
Method removed. Thanks

2023-03-15 13:58 UTC, amcates requested changes

2023-03-15 13:58 UTC, amcates commented on app/models/fulfillment.rb
> -    write_attribute(:invoiced_date, Time.strptime(date_time, "%m/%d/%Y")) if date_time.present?
Did you intend to remove this method?

2023-03-20 13:19 UTC, merged